name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.13.1
          run_install: false

      - name: Generate changelog
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Bundle themes
        run: cd themes && tar -czf iTerm2-theme-vitesse.tar.gz *.itermcolors
        shell: bash

      - name: Fetch release ID
        id: release-id
        run: |
          sleep 5s
          id=$(curl -sL --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/HiDeoo/iTerm2-theme-vitesse/releases/latest | jq -r '.id')
          echo "::set-output name=id::$id"
        shell: bash

      - name: Upload release artifacts
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'themes/*'
          release_id: ${{ steps.release-id.outputs.id }}
